### ISSUE TITLE
Working... for several hours

### ISSUE THREAD

**Issue by miaekim** [JiahaoShan/Glacier-tax-1099-B-Stock-Transactions-Helper#2]
Hello

I am using a this on macbook and I uploaded csv file, it shows `working...` for several hours. I guess it won't take that long time. But I couldn't see any error with the extension but glaciertax.com . Do you have any ideas how can I fix it?

Here is developer console log

Error in response to storage.get: TypeError: Cannot read property 'click' of undefined
    at Object.callback (chrome-extension://mdnkfhpikjbgedlenpdnkhnfhdaohfcm/src/inject/inject.js:94:76)
    at chrome-extension://mdnkfhpikjbgedlenpdnkhnfhdaohfcm/src/inject/inject.js:50:30

I also attached a file I put.
[1099_betterment.zip](https://github.com/JiahaoShan/Glacier-tax-1099-B-Stock-Transactions-Helper/files/869823/1099_betterment.zip)

Thanks

**Comment by miaekim** [comment]
this didn't work because it couldn't find "Add Transaction", if I click "Add Transaction" by hand it works.

<img width="695" alt="screen shot 2017-03-25 at 3 38 17 am" src="https://cloud.githubusercontent.com/assets/2246216/24320489/a5882b46-110c-11e7-89fa-8a4042c58c8a.png">

**Comment by JiahaoShan** [comment]
Thanks for letting me know. I tried your data and it still worked for me magically. If you are still stuck, try to remove the first record and do it again. 
I may dig more into this issue in a few days or if you find this issue interesting, you may make a pull request and try to solve it to help others. 

We know how painful it is to enter transactions one by one by hand.

**Comment by miaekim** [comment]
I solved it by just clicking it "add transaction". Thank you for your help. and I found another issue that it doesn't work for the case 2 or more 1099-B. But since I am solved this issue I will close it.
