### ISSUE TITLE
Disable checking of sum of proceeds with net 1099B proceeds to allow for wash sale.

### ISSUE THREAD

**Issue by anmolnehru** [JiahaoShan/Glacier-tax-1099-B-Stock-Transactions-Helper#4]
There is this concept of wash loss which changes net proceeds which constitute your taxable income. I have a wash loss so in my case, so net proceeds in 1099B is different from the sum of proceeds you calculate by adding up individual rows. Kindly disable the check that you do and return false if the sum doesn't match in inject.js

**Comment by anmolnehru** [comment]
Hi Jiahao, I urge to kindly incorporate this else I'll have to type in all 60+ transactions manually :<

**Comment by JiahaoShan** [comment]
Oh, sure! I am fixing it right now. I got some work to do yesterday

**Comment by JiahaoShan** [comment]
I have fixed it and re-uploaded the extension. It should be effective within an hour. 
Sorry for the AMD though. I am not sure if you still have any, but I do have a large load of that now. still a believer.

**Comment by anmolnehru** [comment]
Haha, just got in a big chunk now, def feel it's undervalued. Big believer
in both it and NVDA.

*Thanks & Regards,*

Anmol Mohanty,

UW-Madison CS MS (2016)
MyWebsite <http://pages.cs.wisc.edu/~amohanty/>

**Comment by JiahaoShan** [comment]
Let me know if the extension works for you. If it does, you may close the issue. 
Good luck to both of us.

**Comment by anmolnehru** [comment]
Hi, it is still not working unfortunately. This is what I get on my page (screenshot attached as well. For some reason the return true isn't working it looks like.

Error code-Total proceeds in the input file doesn't match the total proceeds in the 1099.


![proceeds glacier 1099](https://cloud.githubusercontent.com/assets/9159205/24776406/82c544f4-1ad5-11e7-8aa2-639a112d98d4.JPG)

**Comment by JiahaoShan** [comment]
You may need to manually update the extension. 
Go to chrome://extensions/ and click update extensions now.

**Comment by anmolnehru** [comment]
Yeah reinstalling fixed it. I should have updated you. One thing though it
did automatically populate 4 transactions , rest of the the transactions I
had to press add on glacier per row. Something we can look into I imagine

Anmol Mohanty

MS CS UW-MADISON(2016)
IIMA(dropped)
QUALCOMM(2014)
IITKGP(2013)

**Comment by JiahaoShan** [comment]
I am so sorry for all these hassle. This is so uncool. I think issue #2 had a similar issue, but I cannot figure it out due to the limited test data. Could you make a pull request to help me fix it? I guess it should be a straightforward fix, which is that the jQuery cannot find the element containing the "Add a transaction"

**Comment by anmolnehru** [comment]
Hi Shawn, don't worry about it at all. I will certainly try and fix it.

Meanwhile I had a question about the tax returns(1040NR) in general through
Glacier. Glacier seems to have put my capitals gains under this heading:-

"Schedule NEC—Tax on Income Not Effectively Connected With a U.S. Trade or
Business"

This appears at the end of the form. I was expecting line 14 to get filled

>  ("Capital gain or (loss). Attach Schedule D (Form 1040) if required. If
not required, check here")"

 but that has remained empty for me. This is weird as the businesses are US
ones. Could you check how your 1040NR looks like please?

--Anmol

*Thanks & Regards,*

Anmol Mohanty,

UW-Madison CS MS (2016)
MyWebsite <http://pages.cs.wisc.edu/~amohanty/>

**Comment by JiahaoShan** [comment]
The line 14 is blank for me too. As what I know, if you are a nonresident alien, NEC is for you, not schedule D. For the record, I don't know any more tax issues than you do, but I think you may just leave it like what it was generated. It should be fine. 
Try: https://www.irs.gov/instructions/i1040nr/ch02.html#d0e2080
And: https://www.irs.gov/publications/p519/ch04.html#en_US_2016_publink1000222305

**Comment by Ddey07** [comment]
Hi, 

@anmolnehru , @JiahaoShan , I am filing for Robinhood this year. Does this plugin still work? If yes, how do I take care of wash sale losses disallowed? I emailed GTP and they said that they don't support wash sale loss. Can you please help me in this? I am a non-resident alien for tax purposes. 

Thanks,
Debangan

**Comment by JiahaoShan** [comment]
@Ddey07 I don't have access to Glacier anymore therefore cannot really maintain this repo/plugin. I am not a CPA so that I would suggest you to contact the tax professional in your school or local tax preparation company such as HR Block may provide paid service. Good luck.
